spring:
  datasource:
    url: jdbc:mysql://localhost:3306/find_konstantin_db?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver

spring.jpa:
  properties.hibernate.connection:
    characterEncoding: utf-8
    CharSet: utf-8
    useUnicode: true
  hibernate.ddl-auto: update




#ALTER TABLE find_konstantin_db.user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
